// AUTO-GENERATED by graphql-codegen (T-P0-003). DO NOT EDIT.
// Regenerate via: pnpm --filter @huadian/api codegen
import type { GraphQLResolveInfo, GraphQLScalarType, GraphQLScalarTypeConfig } from 'graphql';
import type { GraphQLContext } from '../context';
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
export type RequireFields<T, K extends keyof T> = Omit<T, K> & { [P in K]-?: NonNullable<T[P]> };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /**
   * ISO 8601 date-time string (UTC, e.g. 2026-04-16T11:16:00Z).
   * Provided by graphql-scalars' DateTimeResolver.
   */
  DateTime: { input: string; output: string; }
  /**
   * Arbitrary JSON value. Use sparingly — prefer concrete types.
   * Provided by graphql-scalars' JSONResolver.
   */
  JSON: { input: unknown; output: unknown; }
  /**
   * Positive integer (>= 1).
   * Provided by graphql-scalars' PositiveIntResolver.
   */
  PositiveInt: { input: number; output: number; }
  /**
   * RFC 4122 UUID string (v4).
   * Provided by graphql-scalars' UUIDResolver.
   */
  UUID: { input: string; output: string; }
};

/**
 * AccountConflict — structured disagreement between two EventAccounts.
 * Replaces v1 version_conflicts (architect Q-2 on T-P0-002). Required for
 * the dual-account story to be usable (architect T-P0-003 #4).
 *
 * diffSummary / analysis remain JSON at Phase 0; a concrete type will be
 * defined alongside the conflict-resolution UI in Phase 1.
 */
export type AccountConflict = {
  __typename?: 'AccountConflict';
  accountAId: Scalars['UUID']['output'];
  accountBId: Scalars['UUID']['output'];
  analysis: Maybe<Scalars['JSON']['output']>;
  conflictType: Maybe<ConflictType>;
  createdAt: Scalars['DateTime']['output'];
  diffSummary: Maybe<Scalars['JSON']['output']>;
  eventId: Scalars['UUID']['output'];
  id: Scalars['ID']['output'];
};

/** Administrative level for historical places / polities (D layer). */
export enum AdminLevel {
  Dao = 'dao',
  Fu = 'fu',
  Guan = 'guan',
  Jun = 'jun',
  Lu = 'lu',
  Other = 'other',
  Xian = 'xian',
  Zhou = 'zhou'
}

/**
 * Book — ancient text metadata (one row per distinct work).
 * Backs packages/db-schema/src/schema/sources.ts → books.
 *
 * Traceable compliance note:
 *   The books table does not carry a dedicated provenanceTier column; the
 *   Traceable.provenanceTier resolver defaults to primary_text (a Book IS the
 *   primary source) and MAY be narrowed by a future resolver that reads
 *   credibilityTier → provenanceTier mapping. sourceEvidenceId resolves to
 *   a representative evidence row for the book (subtask 4 stubs as
 *   NOT_IMPLEMENTED).
 *
 * License note:
 *   The shared-types licenseEnum includes the value "CC-BY" which contains
 *   a hyphen that is illegal in GraphQL enum values. The field is therefore
 *   exposed as String here; resolver guarantees the value matches one of
 *   CC0 / CC-BY / public_domain / proprietary / unknown. A future ADR will
 *   decide whether to rename the shared-types case to CC_BY so we can lift
 *   this back to a typed enum (tracked as L-1 in subtask 7 docs).
 */
export type Book = Traceable & {
  __typename?: 'Book';
  authorPersonId: Maybe<Scalars['UUID']['output']>;
  authoritativeVersion: Maybe<Scalars['String']['output']>;
  credibilityTier: CredibilityTier;
  dynasty: Maybe<Scalars['String']['output']>;
  genre: Maybe<BookGenre>;
  id: Scalars['ID']['output'];
  license: Scalars['String']['output'];
  metadata: Maybe<Scalars['JSON']['output']>;
  provenanceTier: ProvenanceTier;
  slug: Scalars['String']['output'];
  sourceEvidenceId: Scalars['ID']['output'];
  title: MultiLangText;
  updatedAt: Scalars['DateTime']['output'];
};

/** Book genre (A layer). */
export enum BookGenre {
  Classic = 'classic',
  Encyclopedia = 'encyclopedia',
  Geography = 'geography',
  Medical = 'medical',
  Military = 'military',
  OfficialHistory = 'official_history',
  Other = 'other',
  Philosophy = 'philosophy',
  Poetry = 'poetry',
  UnofficialHistory = 'unofficial_history'
}

/**
 * Conflict type between two event accounts (C layer).
 * Backs account_conflicts.conflict_type.
 */
export enum ConflictType {
  Attribution = 'attribution',
  Chronological = 'chronological',
  Factual = 'factual',
  Interpretive = 'interpretive',
  Omission = 'omission'
}

/** Book credibility tier (A layer). */
export enum CredibilityTier {
  Folk = 'folk',
  PrimaryOfficial = 'primary_official',
  PrimaryUnofficial = 'primary_unofficial',
  SecondaryCompilation = 'secondary_compilation',
  TertiaryReference = 'tertiary_reference'
}

/**
 * Date precision classifier used by HistoricalDate.precision.
 * Case MUST match the "precision" enum in
 * packages/shared-types/src/historical-date.ts (R-1 mirror rule extended
 * to shared value types).
 */
export enum DatePrecision {
  Day = 'day',
  Decade = 'decade',
  Era = 'era',
  Month = 'month',
  Unknown = 'unknown',
  Year = 'year',
  YearRange = 'year_range'
}

/**
 * Event — abstract event anchor (see ADR-002). One Event may have multiple
 * EventAccount narratives across different source texts; AccountConflict
 * records structured disagreements between two accounts.
 * Backs packages/db-schema/src/schema/events.ts → events.
 *
 * Related collections (resolved lazily, DataLoader territory per architect #3):
 *   - accounts:  [EventAccount!]!     event_accounts WHERE event_id = this.id
 *   - conflicts: [AccountConflict!]!  account_conflicts WHERE event_id = this.id
 */
export type Event = Traceable & {
  __typename?: 'Event';
  accounts: Array<EventAccount>;
  canonicalAccountId: Maybe<Scalars['UUID']['output']>;
  conflicts: Array<AccountConflict>;
  eventType: Maybe<EventType>;
  id: Scalars['ID']['output'];
  importanceScore: Maybe<Scalars['Float']['output']>;
  placeId: Maybe<Scalars['UUID']['output']>;
  provenanceTier: ProvenanceTier;
  realityStatus: RealityStatus;
  significance: Maybe<MultiLangText>;
  slug: Scalars['String']['output'];
  sourceEvidenceId: Scalars['ID']['output'];
  summary: Maybe<MultiLangText>;
  timePeriodEnd: Maybe<HistoricalDate>;
  timePeriodStart: Maybe<HistoricalDate>;
  title: MultiLangText;
  updatedAt: Scalars['DateTime']['output'];
};

/**
 * EventAccount — one specific narrative of an Event from one source.
 * ADR-002 core table: multi-account coexistence is a constitutional
 * requirement (C-3).
 *
 * JSONB embedded fields (participants / places / sequence) are modeled as
 * typed GraphQL Object Types mirroring shared-types zod schemas; the key
 * mapping from snake_case persisted keys (person_id, place_id) to
 * camelCase GraphQL fields (personId, placeId) happens in resolvers.
 */
export type EventAccount = {
  __typename?: 'EventAccount';
  createdAt: Scalars['DateTime']['output'];
  eventId: Scalars['UUID']['output'];
  id: Scalars['ID']['output'];
  isCanonical: Scalars['Boolean']['output'];
  narrative: MultiLangText;
  participants: Array<EventParticipantRef>;
  places: Array<EventPlaceRef>;
  provenanceTier: ProvenanceTier;
  reliabilityScore: Maybe<Scalars['Float']['output']>;
  sequence: Array<EventSequenceStep>;
  sourceBookId: Maybe<Scalars['UUID']['output']>;
  sourceEvidenceIds: Array<Scalars['UUID']['output']>;
  updatedAt: Scalars['DateTime']['output'];
};

/** Participant within an EventAccount narrative. */
export type EventParticipantRef = {
  __typename?: 'EventParticipantRef';
  action: Maybe<Scalars['String']['output']>;
  personId: Scalars['UUID']['output'];
  role: Scalars['String']['output'];
};

/** Place reference within an EventAccount narrative. */
export type EventPlaceRef = {
  __typename?: 'EventPlaceRef';
  placeId: Scalars['UUID']['output'];
  role: Scalars['String']['output'];
};

/** Ordered step inside the sequence of an EventAccount. */
export type EventSequenceStep = {
  __typename?: 'EventSequenceStep';
  description: MultiLangText;
  order: Scalars['Int']['output'];
  time: Maybe<HistoricalDate>;
};

/** Event type (C layer). */
export enum EventType {
  Cultural = 'cultural',
  Diplomatic = 'diplomatic',
  Economic = 'economic',
  Military = 'military',
  NaturalDisaster = 'natural_disaster',
  Other = 'other',
  Political = 'political',
  Religious = 'religious',
  Social = 'social'
}

/**
 * HistoricalDate — flexible historical date model that supports open-ended
 * ranges, lunar calendar, sexagenary cycle, and reign-era references.
 * Mirrors the JSONB structure defined by historicalDateSchema in
 * @huadian/shared-types.
 *
 * Field name mapping (GraphQL camelCase ↔ JSONB snake_case):
 *   yearMin         ↔  year_min
 *   yearMax         ↔  year_max
 *   reignEra        ↔  reign_era
 *   reignYear       ↔  reign_year
 *   polityId        ↔  polity_id
 *   lunarMonth      ↔  lunar_month
 *   lunarDay        ↔  lunar_day
 *   sexagenaryYear  ↔  sexagenary_year
 *   originalText    ↔  original_text
 */
export type HistoricalDate = {
  __typename?: 'HistoricalDate';
  day: Maybe<Scalars['Int']['output']>;
  lunarDay: Maybe<Scalars['Int']['output']>;
  lunarMonth: Maybe<Scalars['Int']['output']>;
  month: Maybe<Scalars['Int']['output']>;
  originalText: Maybe<Scalars['String']['output']>;
  polityId: Maybe<Scalars['UUID']['output']>;
  precision: DatePrecision;
  reignEra: Maybe<Scalars['String']['output']>;
  reignYear: Maybe<Scalars['PositiveInt']['output']>;
  season: Maybe<Scalars['String']['output']>;
  sexagenaryYear: Maybe<Scalars['String']['output']>;
  yearMax: Maybe<Scalars['Int']['output']>;
  yearMin: Maybe<Scalars['Int']['output']>;
};

/**
 * Identity hypothesis relation type (B layer).
 * See docs/02 §2.2 for examples (Laozi / Li Er / Lao Laizi).
 */
export enum HypothesisRelationType {
  Conflated = 'conflated',
  DistinctDespiteSimilarName = 'distinct_despite_similar_name',
  PossiblySame = 'possibly_same',
  SamePerson = 'same_person'
}

/**
 * IdentityHypothesis — scholarly hypothesis about whether two Person
 * records refer to the same historical figure (e.g. Laozi / Li Er /
 * Lao Laizi). See docs/02 §2.2 and ADR-001.
 *
 * evidenceIds is a JSONB string[] of source_evidences.id UUIDs backing
 * the hypothesis; the architect #3 ruling defers turning this into an
 * embedded SourceEvidence collection to a later DataLoader pass.
 */
export type IdentityHypothesis = {
  __typename?: 'IdentityHypothesis';
  acceptedByDefault: Maybe<Scalars['Boolean']['output']>;
  canonicalPersonId: Scalars['UUID']['output'];
  createdAt: Scalars['DateTime']['output'];
  evidenceIds: Array<Scalars['UUID']['output']>;
  hypothesisPersonId: Maybe<Scalars['UUID']['output']>;
  id: Scalars['ID']['output'];
  notes: Maybe<Scalars['String']['output']>;
  relationType: HypothesisRelationType;
  scholarlySupport: Maybe<Scalars['String']['output']>;
};

/**
 * Multi-language text for user-facing display fields (constitutional
 * requirement C-12). Mirrors the JSONB structure defined by
 * multiLangTextSchema in @huadian/shared-types.
 *
 * Field name mapping between GraphQL (camelCase) and the persisted JSONB
 * keys (language tags with hyphens):
 *   zhHans  ↔  "zh-Hans"  (REQUIRED in source data)
 *   zhHant  ↔  "zh-Hant"
 *   en      ↔  "en"
 */
export type MultiLangText = {
  __typename?: 'MultiLangText';
  en: Maybe<Scalars['String']['output']>;
  zhHans: Scalars['String']['output'];
  zhHant: Maybe<Scalars['String']['output']>;
};

/** Person name type (B layer). */
export enum NameType {
  Alias = 'alias',
  Art = 'art',
  Courtesy = 'courtesy',
  Nickname = 'nickname',
  Posthumous = 'posthumous',
  Primary = 'primary',
  SelfRef = 'self_ref',
  Studio = 'studio',
  Temple = 'temple'
}

/**
 * Person — canonical identity (one row per disambiguated historical or
 * legendary person). Backs packages/db-schema/src/schema/persons.ts → persons.
 *
 * Related collections (resolved lazily, DataLoader territory per architect #3):
 *   - names:              [PersonName!]!           person_names WHERE person_id = this.id
 *   - identityHypotheses: [IdentityHypothesis!]!   identity_hypotheses WHERE canonical_person_id = this.id
 */
export type Person = Traceable & {
  __typename?: 'Person';
  biography: Maybe<MultiLangText>;
  birthDate: Maybe<HistoricalDate>;
  deathDate: Maybe<HistoricalDate>;
  dynasty: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  identityHypotheses: Array<IdentityHypothesis>;
  name: MultiLangText;
  names: Array<PersonName>;
  provenanceTier: ProvenanceTier;
  realityStatus: RealityStatus;
  slug: Scalars['String']['output'];
  sourceEvidenceId: Scalars['ID']['output'];
  updatedAt: Scalars['DateTime']['output'];
};

/**
 * PersonName — one of multiple historical appellations for a Person
 * (courtesy name, posthumous name, nickname, etc.). The canonical name is
 * expressed on Person.name (MultiLangText); PersonName.name is the raw
 * historical string (kept as TEXT per architect Q-3 ruling on T-P0-002).
 *
 * Does not implement Traceable because sourceEvidenceId is nullable here.
 */
export type PersonName = {
  __typename?: 'PersonName';
  createdAt: Scalars['DateTime']['output'];
  endYear: Maybe<Scalars['Int']['output']>;
  id: Scalars['ID']['output'];
  isPrimary: Maybe<Scalars['Boolean']['output']>;
  name: Scalars['String']['output'];
  namePinyin: Maybe<Scalars['String']['output']>;
  nameType: NameType;
  personId: Scalars['UUID']['output'];
  sourceEvidenceId: Maybe<Scalars['UUID']['output']>;
  startYear: Maybe<Scalars['Int']['output']>;
};

/**
 * Place — geographic entity. The PostGIS GEOMETRY column is exposed here
 * as the opaque JSON scalar for Phase 0 (task card explicit non-goal);
 * a typed Geometry model will be introduced in a Phase 1 ADR.
 *
 * Related collections (resolved lazily, DataLoader territory per architect #3):
 *   - names: [PlaceName!]!  place_names WHERE place_id = this.id
 */
export type Place = Traceable & {
  __typename?: 'Place';
  ancientName: Maybe<Scalars['String']['output']>;
  fuzziness: Maybe<Scalars['Float']['output']>;
  geometry: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  modernCountry: Maybe<Scalars['String']['output']>;
  modernName: Maybe<MultiLangText>;
  names: Array<PlaceName>;
  provenanceTier: ProvenanceTier;
  realityStatus: RealityStatus;
  slug: Scalars['String']['output'];
  sourceEvidenceId: Scalars['ID']['output'];
  updatedAt: Scalars['DateTime']['output'];
};

/**
 * PlaceName — a historical name for a Place valid during a specific
 * dynasty / year range. name stays as raw TEXT per architect Q-3 on
 * T-P0-002 (historical proper nouns are not translated).
 *
 * Does not implement Traceable because sourceEvidenceId is nullable here.
 */
export type PlaceName = {
  __typename?: 'PlaceName';
  createdAt: Scalars['DateTime']['output'];
  dynasty: Maybe<Scalars['String']['output']>;
  geometryVariant: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  name: Scalars['String']['output'];
  placeId: Scalars['UUID']['output'];
  sourceEvidenceId: Maybe<Scalars['UUID']['output']>;
  yearEnd: Maybe<Scalars['Int']['output']>;
  yearStart: Maybe<Scalars['Int']['output']>;
};

/**
 * Polity — dynasty or political entity (e.g. 秦, 西汉, 新, 更始, 东汉).
 * Backed by the T-P0-004 batch-1 seed data.
 */
export type Polity = {
  __typename?: 'Polity';
  capitalPlaceId: Maybe<Scalars['UUID']['output']>;
  createdAt: Scalars['DateTime']['output'];
  dynasty: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  metadata: Maybe<Scalars['JSON']['output']>;
  name: MultiLangText;
  slug: Scalars['String']['output'];
  updatedAt: Scalars['DateTime']['output'];
  yearEnd: Maybe<Scalars['Int']['output']>;
  yearStart: Maybe<Scalars['Int']['output']>;
};

/**
 * Provenance tier — constitutional requirement C-2.
 * Required by the Traceable interface (R-1).
 */
export enum ProvenanceTier {
  AiInferred = 'ai_inferred',
  Crowdsourced = 'crowdsourced',
  PrimaryText = 'primary_text',
  ScholarlyConsensus = 'scholarly_consensus',
  Unverified = 'unverified'
}

export type Query = {
  __typename?: 'Query';
  /**
   * Returns the merged SDL snapshot build identifier.
   * Used by CI smoke and local health checks.
   */
  _schemaVersion: Scalars['String']['output'];
  /** Fetch one Event by stable slug. Returns null when absent. */
  event: Maybe<Event>;
  /**
   * Fetch one Person by stable slug (C-13). Returns null when the slug
   * does not match any non-deleted row; an explicit NOT_FOUND error is
   * NOT raised, so that callers can distinguish "absent" from "server
   * error" without inspecting extensions.
   */
  person: Maybe<Person>;
  /**
   * List Persons with offset-based pagination.
   *
   * Arguments:
   *   limit  maximum rows to return; clamped to [1, 100] server-side.
   *   offset number of rows to skip; MUST be non-negative.
   */
  persons: Array<Person>;
  /** Fetch one Place by stable slug. Returns null when absent. */
  place: Maybe<Place>;
  /**
   * Fetch one SourceEvidence by UUID. SourceEvidence is keyed by UUID
   * (not slug) because individual quoted passages do not carry stable
   * human-readable identifiers.
   */
  sourceEvidence: Maybe<SourceEvidence>;
};


export type QueryEventArgs = {
  slug: Scalars['String']['input'];
};


export type QueryPersonArgs = {
  slug: Scalars['String']['input'];
};


export type QueryPersonsArgs = {
  limit?: InputMaybe<Scalars['Int']['input']>;
  offset?: InputMaybe<Scalars['Int']['input']>;
};


export type QueryPlaceArgs = {
  slug: Scalars['String']['input'];
};


export type QuerySourceEvidenceArgs = {
  id: Scalars['UUID']['input'];
};

/**
 * Reality status — applied to persons, events, places, etc.
 * Distinguishes historical records from legend / myth / fiction / composite
 * identities / unknown-category entities.
 */
export enum RealityStatus {
  Composite = 'composite',
  Fictional = 'fictional',
  Historical = 'historical',
  Legendary = 'legendary',
  Mythical = 'mythical',
  Uncertain = 'uncertain'
}

/**
 * ReignEra — named era (年号) within a Polity (e.g. 建元, 元封).
 * name stays as raw TEXT per architect Q-3 on T-P0-002.
 */
export type ReignEra = {
  __typename?: 'ReignEra';
  createdAt: Scalars['DateTime']['output'];
  emperorPersonId: Maybe<Scalars['UUID']['output']>;
  id: Scalars['ID']['output'];
  name: Scalars['String']['output'];
  polityId: Scalars['UUID']['output'];
  updatedAt: Scalars['DateTime']['output'];
  yearEnd: Maybe<Scalars['Int']['output']>;
  yearStart: Scalars['Int']['output'];
};

/**
 * SourceEvidence — atomic unit of provenance (a quoted paragraph from a
 * specific textual version). All other entities link back to this table.
 * Backs packages/db-schema/src/schema/sources.ts → source_evidences.
 *
 * Traceable compliance note:
 *   SourceEvidence self-references: the Traceable.sourceEvidenceId field
 *   resolves to parent.id (evidence IS the evidence). This creates a
 *   deliberate fixed point in the provenance graph.
 */
export type SourceEvidence = Traceable & {
  __typename?: 'SourceEvidence';
  bookId: Maybe<Scalars['UUID']['output']>;
  id: Scalars['ID']['output'];
  llmCallId: Maybe<Scalars['UUID']['output']>;
  positionEnd: Maybe<Scalars['Int']['output']>;
  positionStart: Maybe<Scalars['Int']['output']>;
  promptVersion: Maybe<Scalars['String']['output']>;
  provenanceTier: ProvenanceTier;
  quotedText: Maybe<Scalars['String']['output']>;
  rawTextId: Maybe<Scalars['UUID']['output']>;
  sourceEvidenceId: Scalars['ID']['output'];
  textVersion: Maybe<Scalars['String']['output']>;
  updatedAt: Scalars['DateTime']['output'];
};

/**
 * Traceable — GraphQL-layer enforcement of constitutional article C-2
 * (provenance tracking). Every user-facing entity type MUST implement this
 * interface.
 *
 * Architect ruling R-1 fixes the minimum field set to exactly three fields.
 * Additions / relaxations require a new ADR. The provenanceTier enum case
 * is synced with packages/shared-types/src/enums.ts via codegen; manual
 * edits on either side will be caught by CI.
 */
export type Traceable = {
  provenanceTier: ProvenanceTier;
  sourceEvidenceId: Scalars['ID']['output'];
  updatedAt: Scalars['DateTime']['output'];
};



export type ResolverTypeWrapper<T> = Promise<T> | T;


export type ResolverWithResolve<TResult, TParent, TContext, TArgs> = {
  resolve: ResolverFn<TResult, TParent, TContext, TArgs>;
};
export type Resolver<TResult, TParent = Record<PropertyKey, never>, TContext = Record<PropertyKey, never>, TArgs = Record<PropertyKey, never>> = ResolverFn<TResult, TParent, TContext, TArgs> | ResolverWithResolve<TResult, TParent, TContext, TArgs>;

export type ResolverFn<TResult, TParent, TContext, TArgs> = (
  parent: TParent,
  args: TArgs,
  context: TContext,
  info: GraphQLResolveInfo
) => Promise<TResult> | TResult;

export type SubscriptionSubscribeFn<TResult, TParent, TContext, TArgs> = (
  parent: TParent,
  args: TArgs,
  context: TContext,
  info: GraphQLResolveInfo
) => AsyncIterable<TResult> | Promise<AsyncIterable<TResult>>;

export type SubscriptionResolveFn<TResult, TParent, TContext, TArgs> = (
  parent: TParent,
  args: TArgs,
  context: TContext,
  info: GraphQLResolveInfo
) => TResult | Promise<TResult>;

export interface SubscriptionSubscriberObject<TResult, TKey extends string, TParent, TContext, TArgs> {
  subscribe: SubscriptionSubscribeFn<{ [key in TKey]: TResult }, TParent, TContext, TArgs>;
  resolve?: SubscriptionResolveFn<TResult, { [key in TKey]: TResult }, TContext, TArgs>;
}

export interface SubscriptionResolverObject<TResult, TParent, TContext, TArgs> {
  subscribe: SubscriptionSubscribeFn<any, TParent, TContext, TArgs>;
  resolve: SubscriptionResolveFn<TResult, any, TContext, TArgs>;
}

export type SubscriptionObject<TResult, TKey extends string, TParent, TContext, TArgs> =
  | SubscriptionSubscriberObject<TResult, TKey, TParent, TContext, TArgs>
  | SubscriptionResolverObject<TResult, TParent, TContext, TArgs>;

export type SubscriptionResolver<TResult, TKey extends string, TParent = Record<PropertyKey, never>, TContext = Record<PropertyKey, never>, TArgs = Record<PropertyKey, never>> =
  | ((...args: any[]) => SubscriptionObject<TResult, TKey, TParent, TContext, TArgs>)
  | SubscriptionObject<TResult, TKey, TParent, TContext, TArgs>;

export type TypeResolveFn<TTypes, TParent = Record<PropertyKey, never>, TContext = Record<PropertyKey, never>> = (
  parent: TParent,
  context: TContext,
  info: GraphQLResolveInfo
) => Maybe<TTypes> | Promise<Maybe<TTypes>>;

export type IsTypeOfResolverFn<T = Record<PropertyKey, never>, TContext = Record<PropertyKey, never>> = (obj: T, context: TContext, info: GraphQLResolveInfo) => boolean | Promise<boolean>;

export type NextResolverFn<T> = () => Promise<T>;

export type DirectiveResolverFn<TResult = Record<PropertyKey, never>, TParent = Record<PropertyKey, never>, TContext = Record<PropertyKey, never>, TArgs = Record<PropertyKey, never>> = (
  next: NextResolverFn<TResult>,
  parent: TParent,
  args: TArgs,
  context: TContext,
  info: GraphQLResolveInfo
) => TResult | Promise<TResult>;




/** Mapping of interface types */
export type ResolversInterfaceTypes<_RefType extends Record<string, unknown>> = {
  Traceable:
    | ( Book )
    | ( Event )
    | ( Person )
    | ( Place )
    | ( SourceEvidence )
  ;
};

/** Mapping between all available schema types and the resolvers types */
export type ResolversTypes = {
  AccountConflict: ResolverTypeWrapper<AccountConflict>;
  AdminLevel: AdminLevel;
  Book: ResolverTypeWrapper<Book>;
  BookGenre: BookGenre;
  Boolean: ResolverTypeWrapper<Scalars['Boolean']['output']>;
  ConflictType: ConflictType;
  CredibilityTier: CredibilityTier;
  DatePrecision: DatePrecision;
  DateTime: ResolverTypeWrapper<Scalars['DateTime']['output']>;
  Event: ResolverTypeWrapper<Event>;
  EventAccount: ResolverTypeWrapper<EventAccount>;
  EventParticipantRef: ResolverTypeWrapper<EventParticipantRef>;
  EventPlaceRef: ResolverTypeWrapper<EventPlaceRef>;
  EventSequenceStep: ResolverTypeWrapper<EventSequenceStep>;
  EventType: EventType;
  Float: ResolverTypeWrapper<Scalars['Float']['output']>;
  HistoricalDate: ResolverTypeWrapper<HistoricalDate>;
  HypothesisRelationType: HypothesisRelationType;
  ID: ResolverTypeWrapper<Scalars['ID']['output']>;
  IdentityHypothesis: ResolverTypeWrapper<IdentityHypothesis>;
  Int: ResolverTypeWrapper<Scalars['Int']['output']>;
  JSON: ResolverTypeWrapper<Scalars['JSON']['output']>;
  MultiLangText: ResolverTypeWrapper<MultiLangText>;
  NameType: NameType;
  Person: ResolverTypeWrapper<Person>;
  PersonName: ResolverTypeWrapper<PersonName>;
  Place: ResolverTypeWrapper<Place>;
  PlaceName: ResolverTypeWrapper<PlaceName>;
  Polity: ResolverTypeWrapper<Polity>;
  PositiveInt: ResolverTypeWrapper<Scalars['PositiveInt']['output']>;
  ProvenanceTier: ProvenanceTier;
  Query: ResolverTypeWrapper<Record<PropertyKey, never>>;
  RealityStatus: RealityStatus;
  ReignEra: ResolverTypeWrapper<ReignEra>;
  SourceEvidence: ResolverTypeWrapper<SourceEvidence>;
  String: ResolverTypeWrapper<Scalars['String']['output']>;
  Traceable: ResolverTypeWrapper<ResolversInterfaceTypes<ResolversTypes>['Traceable']>;
  UUID: ResolverTypeWrapper<Scalars['UUID']['output']>;
};

/** Mapping between all available schema types and the resolvers parents */
export type ResolversParentTypes = {
  AccountConflict: AccountConflict;
  Book: Book;
  Boolean: Scalars['Boolean']['output'];
  DateTime: Scalars['DateTime']['output'];
  Event: Event;
  EventAccount: EventAccount;
  EventParticipantRef: EventParticipantRef;
  EventPlaceRef: EventPlaceRef;
  EventSequenceStep: EventSequenceStep;
  Float: Scalars['Float']['output'];
  HistoricalDate: HistoricalDate;
  ID: Scalars['ID']['output'];
  IdentityHypothesis: IdentityHypothesis;
  Int: Scalars['Int']['output'];
  JSON: Scalars['JSON']['output'];
  MultiLangText: MultiLangText;
  Person: Person;
  PersonName: PersonName;
  Place: Place;
  PlaceName: PlaceName;
  Polity: Polity;
  PositiveInt: Scalars['PositiveInt']['output'];
  Query: Record<PropertyKey, never>;
  ReignEra: ReignEra;
  SourceEvidence: SourceEvidence;
  String: Scalars['String']['output'];
  Traceable: ResolversInterfaceTypes<ResolversParentTypes>['Traceable'];
  UUID: Scalars['UUID']['output'];
};

export type AccountConflictResolvers<ContextType = GraphQLContext, ParentType extends ResolversParentTypes['AccountConflict'] = ResolversParentTypes['AccountConflict']> = {
  accountAId?: Resolver<ResolversTypes['UUID'], ParentType, ContextType>;
  accountBId?: Resolver<ResolversTypes['UUID'], ParentType, ContextType>;
  analysis?: Resolver<Maybe<ResolversTypes['JSON']>, ParentType, ContextType>;
  conflictType?: Resolver<Maybe<ResolversTypes['ConflictType']>, ParentType, ContextType>;
  createdAt?: Resolver<ResolversTypes['DateTime'], ParentType, ContextType>;
  diffSummary?: Resolver<Maybe<ResolversTypes['JSON']>, ParentType, ContextType>;
  eventId?: Resolver<ResolversTypes['UUID'], ParentType, ContextType>;
  id?: Resolver<ResolversTypes['ID'], ParentType, ContextType>;
};

export type BookResolvers<ContextType = GraphQLContext, ParentType extends ResolversParentTypes['Book'] = ResolversParentTypes['Book']> = {
  authorPersonId?: Resolver<Maybe<ResolversTypes['UUID']>, ParentType, ContextType>;
  authoritativeVersion?: Resolver<Maybe<ResolversTypes['String']>, ParentType, ContextType>;
  credibilityTier?: Resolver<ResolversTypes['CredibilityTier'], ParentType, ContextType>;
  dynasty?: Resolver<Maybe<ResolversTypes['String']>, ParentType, ContextType>;
  genre?: Resolver<Maybe<ResolversTypes['BookGenre']>, ParentType, ContextType>;
  id?: Resolver<ResolversTypes['ID'], ParentType, ContextType>;
  license?: Resolver<ResolversTypes['String'], ParentType, ContextType>;
  metadata?: Resolver<Maybe<ResolversTypes['JSON']>, ParentType, ContextType>;
  provenanceTier?: Resolver<ResolversTypes['ProvenanceTier'], ParentType, ContextType>;
  slug?: Resolver<ResolversTypes['String'], ParentType, ContextType>;
  sourceEvidenceId?: Resolver<ResolversTypes['ID'], ParentType, ContextType>;
  title?: Resolver<ResolversTypes['MultiLangText'], ParentType, ContextType>;
  updatedAt?: Resolver<ResolversTypes['DateTime'], ParentType, ContextType>;
  __isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
};

export interface DateTimeScalarConfig extends GraphQLScalarTypeConfig<ResolversTypes['DateTime'], any> {
  name: 'DateTime';
}

export type EventResolvers<ContextType = GraphQLContext, ParentType extends ResolversParentTypes['Event'] = ResolversParentTypes['Event']> = {
  accounts?: Resolver<Array<ResolversTypes['EventAccount']>, ParentType, ContextType>;
  canonicalAccountId?: Resolver<Maybe<ResolversTypes['UUID']>, ParentType, ContextType>;
  conflicts?: Resolver<Array<ResolversTypes['AccountConflict']>, ParentType, ContextType>;
  eventType?: Resolver<Maybe<ResolversTypes['EventType']>, ParentType, ContextType>;
  id?: Resolver<ResolversTypes['ID'], ParentType, ContextType>;
  importanceScore?: Resolver<Maybe<ResolversTypes['Float']>, ParentType, ContextType>;
  placeId?: Resolver<Maybe<ResolversTypes['UUID']>, ParentType, ContextType>;
  provenanceTier?: Resolver<ResolversTypes['ProvenanceTier'], ParentType, ContextType>;
  realityStatus?: Resolver<ResolversTypes['RealityStatus'], ParentType, ContextType>;
  significance?: Resolver<Maybe<ResolversTypes['MultiLangText']>, ParentType, ContextType>;
  slug?: Resolver<ResolversTypes['String'], ParentType, ContextType>;
  sourceEvidenceId?: Resolver<ResolversTypes['ID'], ParentType, ContextType>;
  summary?: Resolver<Maybe<ResolversTypes['MultiLangText']>, ParentType, ContextType>;
  timePeriodEnd?: Resolver<Maybe<ResolversTypes['HistoricalDate']>, ParentType, ContextType>;
  timePeriodStart?: Resolver<Maybe<ResolversTypes['HistoricalDate']>, ParentType, ContextType>;
  title?: Resolver<ResolversTypes['MultiLangText'], ParentType, ContextType>;
  updatedAt?: Resolver<ResolversTypes['DateTime'], ParentType, ContextType>;
  __isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
};

export type EventAccountResolvers<ContextType = GraphQLContext, ParentType extends ResolversParentTypes['EventAccount'] = ResolversParentTypes['EventAccount']> = {
  createdAt?: Resolver<ResolversTypes['DateTime'], ParentType, ContextType>;
  eventId?: Resolver<ResolversTypes['UUID'], ParentType, ContextType>;
  id?: Resolver<ResolversTypes['ID'], ParentType, ContextType>;
  isCanonical?: Resolver<ResolversTypes['Boolean'], ParentType, ContextType>;
  narrative?: Resolver<ResolversTypes['MultiLangText'], ParentType, ContextType>;
  participants?: Resolver<Array<ResolversTypes['EventParticipantRef']>, ParentType, ContextType>;
  places?: Resolver<Array<ResolversTypes['EventPlaceRef']>, ParentType, ContextType>;
  provenanceTier?: Resolver<ResolversTypes['ProvenanceTier'], ParentType, ContextType>;
  reliabilityScore?: Resolver<Maybe<ResolversTypes['Float']>, ParentType, ContextType>;
  sequence?: Resolver<Array<ResolversTypes['EventSequenceStep']>, ParentType, ContextType>;
  sourceBookId?: Resolver<Maybe<ResolversTypes['UUID']>, ParentType, ContextType>;
  sourceEvidenceIds?: Resolver<Array<ResolversTypes['UUID']>, ParentType, ContextType>;
  updatedAt?: Resolver<ResolversTypes['DateTime'], ParentType, ContextType>;
};

export type EventParticipantRefResolvers<ContextType = GraphQLContext, ParentType extends ResolversParentTypes['EventParticipantRef'] = ResolversParentTypes['EventParticipantRef']> = {
  action?: Resolver<Maybe<ResolversTypes['String']>, ParentType, ContextType>;
  personId?: Resolver<ResolversTypes['UUID'], ParentType, ContextType>;
  role?: Resolver<ResolversTypes['String'], ParentType, ContextType>;
};

export type EventPlaceRefResolvers<ContextType = GraphQLContext, ParentType extends ResolversParentTypes['EventPlaceRef'] = ResolversParentTypes['EventPlaceRef']> = {
  placeId?: Resolver<ResolversTypes['UUID'], ParentType, ContextType>;
  role?: Resolver<ResolversTypes['String'], ParentType, ContextType>;
};

export type EventSequenceStepResolvers<ContextType = GraphQLContext, ParentType extends ResolversParentTypes['EventSequenceStep'] = ResolversParentTypes['EventSequenceStep']> = {
  description?: Resolver<ResolversTypes['MultiLangText'], ParentType, ContextType>;
  order?: Resolver<ResolversTypes['Int'], ParentType, ContextType>;
  time?: Resolver<Maybe<ResolversTypes['HistoricalDate']>, ParentType, ContextType>;
};

export type HistoricalDateResolvers<ContextType = GraphQLContext, ParentType extends ResolversParentTypes['HistoricalDate'] = ResolversParentTypes['HistoricalDate']> = {
  day?: Resolver<Maybe<ResolversTypes['Int']>, ParentType, ContextType>;
  lunarDay?: Resolver<Maybe<ResolversTypes['Int']>, ParentType, ContextType>;
  lunarMonth?: Resolver<Maybe<ResolversTypes['Int']>, ParentType, ContextType>;
  month?: Resolver<Maybe<ResolversTypes['Int']>, ParentType, ContextType>;
  originalText?: Resolver<Maybe<ResolversTypes['String']>, ParentType, ContextType>;
  polityId?: Resolver<Maybe<ResolversTypes['UUID']>, ParentType, ContextType>;
  precision?: Resolver<ResolversTypes['DatePrecision'], ParentType, ContextType>;
  reignEra?: Resolver<Maybe<ResolversTypes['String']>, ParentType, ContextType>;
  reignYear?: Resolver<Maybe<ResolversTypes['PositiveInt']>, ParentType, ContextType>;
  season?: Resolver<Maybe<ResolversTypes['String']>, ParentType, ContextType>;
  sexagenaryYear?: Resolver<Maybe<ResolversTypes['String']>, ParentType, ContextType>;
  yearMax?: Resolver<Maybe<ResolversTypes['Int']>, ParentType, ContextType>;
  yearMin?: Resolver<Maybe<ResolversTypes['Int']>, ParentType, ContextType>;
};

export type IdentityHypothesisResolvers<ContextType = GraphQLContext, ParentType extends ResolversParentTypes['IdentityHypothesis'] = ResolversParentTypes['IdentityHypothesis']> = {
  acceptedByDefault?: Resolver<Maybe<ResolversTypes['Boolean']>, ParentType, ContextType>;
  canonicalPersonId?: Resolver<ResolversTypes['UUID'], ParentType, ContextType>;
  createdAt?: Resolver<ResolversTypes['DateTime'], ParentType, ContextType>;
  evidenceIds?: Resolver<Array<ResolversTypes['UUID']>, ParentType, ContextType>;
  hypothesisPersonId?: Resolver<Maybe<ResolversTypes['UUID']>, ParentType, ContextType>;
  id?: Resolver<ResolversTypes['ID'], ParentType, ContextType>;
  notes?: Resolver<Maybe<ResolversTypes['String']>, ParentType, ContextType>;
  relationType?: Resolver<ResolversTypes['HypothesisRelationType'], ParentType, ContextType>;
  scholarlySupport?: Resolver<Maybe<ResolversTypes['String']>, ParentType, ContextType>;
};

export interface JsonScalarConfig extends GraphQLScalarTypeConfig<ResolversTypes['JSON'], any> {
  name: 'JSON';
}

export type MultiLangTextResolvers<ContextType = GraphQLContext, ParentType extends ResolversParentTypes['MultiLangText'] = ResolversParentTypes['MultiLangText']> = {
  en?: Resolver<Maybe<ResolversTypes['String']>, ParentType, ContextType>;
  zhHans?: Resolver<ResolversTypes['String'], ParentType, ContextType>;
  zhHant?: Resolver<Maybe<ResolversTypes['String']>, ParentType, ContextType>;
};

export type PersonResolvers<ContextType = GraphQLContext, ParentType extends ResolversParentTypes['Person'] = ResolversParentTypes['Person']> = {
  biography?: Resolver<Maybe<ResolversTypes['MultiLangText']>, ParentType, ContextType>;
  birthDate?: Resolver<Maybe<ResolversTypes['HistoricalDate']>, ParentType, ContextType>;
  deathDate?: Resolver<Maybe<ResolversTypes['HistoricalDate']>, ParentType, ContextType>;
  dynasty?: Resolver<Maybe<ResolversTypes['String']>, ParentType, ContextType>;
  id?: Resolver<ResolversTypes['ID'], ParentType, ContextType>;
  identityHypotheses?: Resolver<Array<ResolversTypes['IdentityHypothesis']>, ParentType, ContextType>;
  name?: Resolver<ResolversTypes['MultiLangText'], ParentType, ContextType>;
  names?: Resolver<Array<ResolversTypes['PersonName']>, ParentType, ContextType>;
  provenanceTier?: Resolver<ResolversTypes['ProvenanceTier'], ParentType, ContextType>;
  realityStatus?: Resolver<ResolversTypes['RealityStatus'], ParentType, ContextType>;
  slug?: Resolver<ResolversTypes['String'], ParentType, ContextType>;
  sourceEvidenceId?: Resolver<ResolversTypes['ID'], ParentType, ContextType>;
  updatedAt?: Resolver<ResolversTypes['DateTime'], ParentType, ContextType>;
  __isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
};

export type PersonNameResolvers<ContextType = GraphQLContext, ParentType extends ResolversParentTypes['PersonName'] = ResolversParentTypes['PersonName']> = {
  createdAt?: Resolver<ResolversTypes['DateTime'], ParentType, ContextType>;
  endYear?: Resolver<Maybe<ResolversTypes['Int']>, ParentType, ContextType>;
  id?: Resolver<ResolversTypes['ID'], ParentType, ContextType>;
  isPrimary?: Resolver<Maybe<ResolversTypes['Boolean']>, ParentType, ContextType>;
  name?: Resolver<ResolversTypes['String'], ParentType, ContextType>;
  namePinyin?: Resolver<Maybe<ResolversTypes['String']>, ParentType, ContextType>;
  nameType?: Resolver<ResolversTypes['NameType'], ParentType, ContextType>;
  personId?: Resolver<ResolversTypes['UUID'], ParentType, ContextType>;
  sourceEvidenceId?: Resolver<Maybe<ResolversTypes['UUID']>, ParentType, ContextType>;
  startYear?: Resolver<Maybe<ResolversTypes['Int']>, ParentType, ContextType>;
};

export type PlaceResolvers<ContextType = GraphQLContext, ParentType extends ResolversParentTypes['Place'] = ResolversParentTypes['Place']> = {
  ancientName?: Resolver<Maybe<ResolversTypes['String']>, ParentType, ContextType>;
  fuzziness?: Resolver<Maybe<ResolversTypes['Float']>, ParentType, ContextType>;
  geometry?: Resolver<Maybe<ResolversTypes['JSON']>, ParentType, ContextType>;
  id?: Resolver<ResolversTypes['ID'], ParentType, ContextType>;
  modernCountry?: Resolver<Maybe<ResolversTypes['String']>, ParentType, ContextType>;
  modernName?: Resolver<Maybe<ResolversTypes['MultiLangText']>, ParentType, ContextType>;
  names?: Resolver<Array<ResolversTypes['PlaceName']>, ParentType, ContextType>;
  provenanceTier?: Resolver<ResolversTypes['ProvenanceTier'], ParentType, ContextType>;
  realityStatus?: Resolver<ResolversTypes['RealityStatus'], ParentType, ContextType>;
  slug?: Resolver<ResolversTypes['String'], ParentType, ContextType>;
  sourceEvidenceId?: Resolver<ResolversTypes['ID'], ParentType, ContextType>;
  updatedAt?: Resolver<ResolversTypes['DateTime'], ParentType, ContextType>;
  __isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
};

export type PlaceNameResolvers<ContextType = GraphQLContext, ParentType extends ResolversParentTypes['PlaceName'] = ResolversParentTypes['PlaceName']> = {
  createdAt?: Resolver<ResolversTypes['DateTime'], ParentType, ContextType>;
  dynasty?: Resolver<Maybe<ResolversTypes['String']>, ParentType, ContextType>;
  geometryVariant?: Resolver<Maybe<ResolversTypes['JSON']>, ParentType, ContextType>;
  id?: Resolver<ResolversTypes['ID'], ParentType, ContextType>;
  name?: Resolver<ResolversTypes['String'], ParentType, ContextType>;
  placeId?: Resolver<ResolversTypes['UUID'], ParentType, ContextType>;
  sourceEvidenceId?: Resolver<Maybe<ResolversTypes['UUID']>, ParentType, ContextType>;
  yearEnd?: Resolver<Maybe<ResolversTypes['Int']>, ParentType, ContextType>;
  yearStart?: Resolver<Maybe<ResolversTypes['Int']>, ParentType, ContextType>;
};

export type PolityResolvers<ContextType = GraphQLContext, ParentType extends ResolversParentTypes['Polity'] = ResolversParentTypes['Polity']> = {
  capitalPlaceId?: Resolver<Maybe<ResolversTypes['UUID']>, ParentType, ContextType>;
  createdAt?: Resolver<ResolversTypes['DateTime'], ParentType, ContextType>;
  dynasty?: Resolver<Maybe<ResolversTypes['String']>, ParentType, ContextType>;
  id?: Resolver<ResolversTypes['ID'], ParentType, ContextType>;
  metadata?: Resolver<Maybe<ResolversTypes['JSON']>, ParentType, ContextType>;
  name?: Resolver<ResolversTypes['MultiLangText'], ParentType, ContextType>;
  slug?: Resolver<ResolversTypes['String'], ParentType, ContextType>;
  updatedAt?: Resolver<ResolversTypes['DateTime'], ParentType, ContextType>;
  yearEnd?: Resolver<Maybe<ResolversTypes['Int']>, ParentType, ContextType>;
  yearStart?: Resolver<Maybe<ResolversTypes['Int']>, ParentType, ContextType>;
};

export interface PositiveIntScalarConfig extends GraphQLScalarTypeConfig<ResolversTypes['PositiveInt'], any> {
  name: 'PositiveInt';
}

export type QueryResolvers<ContextType = GraphQLContext, ParentType extends ResolversParentTypes['Query'] = ResolversParentTypes['Query']> = {
  _schemaVersion?: Resolver<ResolversTypes['String'], ParentType, ContextType>;
  event?: Resolver<Maybe<ResolversTypes['Event']>, ParentType, ContextType, RequireFields<QueryEventArgs, 'slug'>>;
  person?: Resolver<Maybe<ResolversTypes['Person']>, ParentType, ContextType, RequireFields<QueryPersonArgs, 'slug'>>;
  persons?: Resolver<Array<ResolversTypes['Person']>, ParentType, ContextType, RequireFields<QueryPersonsArgs, 'limit' | 'offset'>>;
  place?: Resolver<Maybe<ResolversTypes['Place']>, ParentType, ContextType, RequireFields<QueryPlaceArgs, 'slug'>>;
  sourceEvidence?: Resolver<Maybe<ResolversTypes['SourceEvidence']>, ParentType, ContextType, RequireFields<QuerySourceEvidenceArgs, 'id'>>;
};

export type ReignEraResolvers<ContextType = GraphQLContext, ParentType extends ResolversParentTypes['ReignEra'] = ResolversParentTypes['ReignEra']> = {
  createdAt?: Resolver<ResolversTypes['DateTime'], ParentType, ContextType>;
  emperorPersonId?: Resolver<Maybe<ResolversTypes['UUID']>, ParentType, ContextType>;
  id?: Resolver<ResolversTypes['ID'], ParentType, ContextType>;
  name?: Resolver<ResolversTypes['String'], ParentType, ContextType>;
  polityId?: Resolver<ResolversTypes['UUID'], ParentType, ContextType>;
  updatedAt?: Resolver<ResolversTypes['DateTime'], ParentType, ContextType>;
  yearEnd?: Resolver<Maybe<ResolversTypes['Int']>, ParentType, ContextType>;
  yearStart?: Resolver<ResolversTypes['Int'], ParentType, ContextType>;
};

export type SourceEvidenceResolvers<ContextType = GraphQLContext, ParentType extends ResolversParentTypes['SourceEvidence'] = ResolversParentTypes['SourceEvidence']> = {
  bookId?: Resolver<Maybe<ResolversTypes['UUID']>, ParentType, ContextType>;
  id?: Resolver<ResolversTypes['ID'], ParentType, ContextType>;
  llmCallId?: Resolver<Maybe<ResolversTypes['UUID']>, ParentType, ContextType>;
  positionEnd?: Resolver<Maybe<ResolversTypes['Int']>, ParentType, ContextType>;
  positionStart?: Resolver<Maybe<ResolversTypes['Int']>, ParentType, ContextType>;
  promptVersion?: Resolver<Maybe<ResolversTypes['String']>, ParentType, ContextType>;
  provenanceTier?: Resolver<ResolversTypes['ProvenanceTier'], ParentType, ContextType>;
  quotedText?: Resolver<Maybe<ResolversTypes['String']>, ParentType, ContextType>;
  rawTextId?: Resolver<Maybe<ResolversTypes['UUID']>, ParentType, ContextType>;
  sourceEvidenceId?: Resolver<ResolversTypes['ID'], ParentType, ContextType>;
  textVersion?: Resolver<Maybe<ResolversTypes['String']>, ParentType, ContextType>;
  updatedAt?: Resolver<ResolversTypes['DateTime'], ParentType, ContextType>;
  __isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
};

export type TraceableResolvers<ContextType = GraphQLContext, ParentType extends ResolversParentTypes['Traceable'] = ResolversParentTypes['Traceable']> = {
  __resolveType: TypeResolveFn<'Book' | 'Event' | 'Person' | 'Place' | 'SourceEvidence', ParentType, ContextType>;
};

export interface UuidScalarConfig extends GraphQLScalarTypeConfig<ResolversTypes['UUID'], any> {
  name: 'UUID';
}

export type Resolvers<ContextType = GraphQLContext> = {
  AccountConflict?: AccountConflictResolvers<ContextType>;
  Book?: BookResolvers<ContextType>;
  DateTime?: GraphQLScalarType;
  Event?: EventResolvers<ContextType>;
  EventAccount?: EventAccountResolvers<ContextType>;
  EventParticipantRef?: EventParticipantRefResolvers<ContextType>;
  EventPlaceRef?: EventPlaceRefResolvers<ContextType>;
  EventSequenceStep?: EventSequenceStepResolvers<ContextType>;
  HistoricalDate?: HistoricalDateResolvers<ContextType>;
  IdentityHypothesis?: IdentityHypothesisResolvers<ContextType>;
  JSON?: GraphQLScalarType;
  MultiLangText?: MultiLangTextResolvers<ContextType>;
  Person?: PersonResolvers<ContextType>;
  PersonName?: PersonNameResolvers<ContextType>;
  Place?: PlaceResolvers<ContextType>;
  PlaceName?: PlaceNameResolvers<ContextType>;
  Polity?: PolityResolvers<ContextType>;
  PositiveInt?: GraphQLScalarType;
  Query?: QueryResolvers<ContextType>;
  ReignEra?: ReignEraResolvers<ContextType>;
  SourceEvidence?: SourceEvidenceResolvers<ContextType>;
  Traceable?: TraceableResolvers<ContextType>;
  UUID?: GraphQLScalarType;
};

