// AUTO-GENERATED by graphql-codegen (T-P0-003). DO NOT EDIT.
// Regenerate via: pnpm --filter @huadian/api codegen
import type { GraphQLResolveInfo, GraphQLScalarType, GraphQLScalarTypeConfig } from 'graphql';
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /**
   * ISO 8601 date-time string (UTC, e.g. 2026-04-16T11:16:00Z).
   * Provided by graphql-scalars' DateTimeResolver.
   */
  DateTime: { input: string; output: string; }
  /**
   * Arbitrary JSON value. Use sparingly — prefer concrete types.
   * Provided by graphql-scalars' JSONResolver.
   */
  JSON: { input: unknown; output: unknown; }
  /**
   * Positive integer (>= 1).
   * Provided by graphql-scalars' PositiveIntResolver.
   */
  PositiveInt: { input: number; output: number; }
  /**
   * RFC 4122 UUID string (v4).
   * Provided by graphql-scalars' UUIDResolver.
   */
  UUID: { input: string; output: string; }
};

/** Administrative level for historical places / polities (D layer). */
export enum AdminLevel {
  Dao = 'dao',
  Fu = 'fu',
  Guan = 'guan',
  Jun = 'jun',
  Lu = 'lu',
  Other = 'other',
  Xian = 'xian',
  Zhou = 'zhou'
}

/** Book genre (A layer). */
export enum BookGenre {
  Classic = 'classic',
  Encyclopedia = 'encyclopedia',
  Geography = 'geography',
  Medical = 'medical',
  Military = 'military',
  OfficialHistory = 'official_history',
  Other = 'other',
  Philosophy = 'philosophy',
  Poetry = 'poetry',
  UnofficialHistory = 'unofficial_history'
}

/**
 * Conflict type between two event accounts (C layer).
 * Backs account_conflicts.conflict_type.
 */
export enum ConflictType {
  Attribution = 'attribution',
  Chronological = 'chronological',
  Factual = 'factual',
  Interpretive = 'interpretive',
  Omission = 'omission'
}

/** Book credibility tier (A layer). */
export enum CredibilityTier {
  Folk = 'folk',
  PrimaryOfficial = 'primary_official',
  PrimaryUnofficial = 'primary_unofficial',
  SecondaryCompilation = 'secondary_compilation',
  TertiaryReference = 'tertiary_reference'
}

/**
 * Date precision classifier used by HistoricalDate.precision.
 * Case MUST match the "precision" enum in
 * packages/shared-types/src/historical-date.ts (R-1 mirror rule extended
 * to shared value types).
 */
export enum DatePrecision {
  Day = 'day',
  Decade = 'decade',
  Era = 'era',
  Month = 'month',
  Unknown = 'unknown',
  Year = 'year',
  YearRange = 'year_range'
}

/** Event type (C layer). */
export enum EventType {
  Cultural = 'cultural',
  Diplomatic = 'diplomatic',
  Economic = 'economic',
  Military = 'military',
  NaturalDisaster = 'natural_disaster',
  Other = 'other',
  Political = 'political',
  Religious = 'religious',
  Social = 'social'
}

/**
 * HistoricalDate — flexible historical date model that supports open-ended
 * ranges, lunar calendar, sexagenary cycle, and reign-era references.
 * Mirrors the JSONB structure defined by historicalDateSchema in
 * @huadian/shared-types.
 *
 * Field name mapping (GraphQL camelCase ↔ JSONB snake_case):
 *   yearMin         ↔  year_min
 *   yearMax         ↔  year_max
 *   reignEra        ↔  reign_era
 *   reignYear       ↔  reign_year
 *   polityId        ↔  polity_id
 *   lunarMonth      ↔  lunar_month
 *   lunarDay        ↔  lunar_day
 *   sexagenaryYear  ↔  sexagenary_year
 *   originalText    ↔  original_text
 */
export type HistoricalDate = {
  __typename?: 'HistoricalDate';
  day: Maybe<Scalars['Int']['output']>;
  lunarDay: Maybe<Scalars['Int']['output']>;
  lunarMonth: Maybe<Scalars['Int']['output']>;
  month: Maybe<Scalars['Int']['output']>;
  originalText: Maybe<Scalars['String']['output']>;
  polityId: Maybe<Scalars['UUID']['output']>;
  precision: DatePrecision;
  reignEra: Maybe<Scalars['String']['output']>;
  reignYear: Maybe<Scalars['PositiveInt']['output']>;
  season: Maybe<Scalars['String']['output']>;
  sexagenaryYear: Maybe<Scalars['String']['output']>;
  yearMax: Maybe<Scalars['Int']['output']>;
  yearMin: Maybe<Scalars['Int']['output']>;
};

/**
 * Identity hypothesis relation type (B layer).
 * See docs/02 §2.2 for examples (Laozi / Li Er / Lao Laizi).
 */
export enum HypothesisRelationType {
  Conflated = 'conflated',
  DistinctDespiteSimilarName = 'distinct_despite_similar_name',
  PossiblySame = 'possibly_same',
  SamePerson = 'same_person'
}

/**
 * Multi-language text for user-facing display fields (constitutional
 * requirement C-12). Mirrors the JSONB structure defined by
 * multiLangTextSchema in @huadian/shared-types.
 *
 * Field name mapping between GraphQL (camelCase) and the persisted JSONB
 * keys (language tags with hyphens):
 *   zhHans  ↔  "zh-Hans"  (REQUIRED in source data)
 *   zhHant  ↔  "zh-Hant"
 *   en      ↔  "en"
 */
export type MultiLangText = {
  __typename?: 'MultiLangText';
  en: Maybe<Scalars['String']['output']>;
  zhHans: Scalars['String']['output'];
  zhHant: Maybe<Scalars['String']['output']>;
};

/** Person name type (B layer). */
export enum NameType {
  Alias = 'alias',
  Art = 'art',
  Courtesy = 'courtesy',
  Nickname = 'nickname',
  Posthumous = 'posthumous',
  Primary = 'primary',
  SelfRef = 'self_ref',
  Studio = 'studio',
  Temple = 'temple'
}

/**
 * Provenance tier — constitutional requirement C-2.
 * Required by the Traceable interface (R-1).
 */
export enum ProvenanceTier {
  AiInferred = 'ai_inferred',
  Crowdsourced = 'crowdsourced',
  PrimaryText = 'primary_text',
  ScholarlyConsensus = 'scholarly_consensus',
  Unverified = 'unverified'
}

export type Query = {
  __typename?: 'Query';
  /**
   * Returns the merged SDL snapshot build identifier.
   * Used by CI smoke and local health checks.
   */
  _schemaVersion: Scalars['String']['output'];
};

/**
 * Reality status — applied to persons, events, places, etc.
 * Distinguishes historical records from legend / myth / fiction / composite
 * identities / unknown-category entities.
 */
export enum RealityStatus {
  Composite = 'composite',
  Fictional = 'fictional',
  Historical = 'historical',
  Legendary = 'legendary',
  Mythical = 'mythical',
  Uncertain = 'uncertain'
}

/**
 * Traceable — GraphQL-layer enforcement of constitutional article C-2
 * (provenance tracking). Every user-facing entity type MUST implement this
 * interface.
 *
 * Architect ruling R-1 fixes the minimum field set to exactly three fields.
 * Additions / relaxations require a new ADR. The provenanceTier enum case
 * is synced with packages/shared-types/src/enums.ts via codegen; manual
 * edits on either side will be caught by CI.
 */
export type Traceable = {
  provenanceTier: ProvenanceTier;
  sourceEvidenceId: Scalars['ID']['output'];
  updatedAt: Scalars['DateTime']['output'];
};



export type ResolverTypeWrapper<T> = Promise<T> | T;


export type ResolverWithResolve<TResult, TParent, TContext, TArgs> = {
  resolve: ResolverFn<TResult, TParent, TContext, TArgs>;
};
export type Resolver<TResult, TParent = Record<PropertyKey, never>, TContext = Record<PropertyKey, never>, TArgs = Record<PropertyKey, never>> = ResolverFn<TResult, TParent, TContext, TArgs> | ResolverWithResolve<TResult, TParent, TContext, TArgs>;

export type ResolverFn<TResult, TParent, TContext, TArgs> = (
  parent: TParent,
  args: TArgs,
  context: TContext,
  info: GraphQLResolveInfo
) => Promise<TResult> | TResult;

export type SubscriptionSubscribeFn<TResult, TParent, TContext, TArgs> = (
  parent: TParent,
  args: TArgs,
  context: TContext,
  info: GraphQLResolveInfo
) => AsyncIterable<TResult> | Promise<AsyncIterable<TResult>>;

export type SubscriptionResolveFn<TResult, TParent, TContext, TArgs> = (
  parent: TParent,
  args: TArgs,
  context: TContext,
  info: GraphQLResolveInfo
) => TResult | Promise<TResult>;

export interface SubscriptionSubscriberObject<TResult, TKey extends string, TParent, TContext, TArgs> {
  subscribe: SubscriptionSubscribeFn<{ [key in TKey]: TResult }, TParent, TContext, TArgs>;
  resolve?: SubscriptionResolveFn<TResult, { [key in TKey]: TResult }, TContext, TArgs>;
}

export interface SubscriptionResolverObject<TResult, TParent, TContext, TArgs> {
  subscribe: SubscriptionSubscribeFn<any, TParent, TContext, TArgs>;
  resolve: SubscriptionResolveFn<TResult, any, TContext, TArgs>;
}

export type SubscriptionObject<TResult, TKey extends string, TParent, TContext, TArgs> =
  | SubscriptionSubscriberObject<TResult, TKey, TParent, TContext, TArgs>
  | SubscriptionResolverObject<TResult, TParent, TContext, TArgs>;

export type SubscriptionResolver<TResult, TKey extends string, TParent = Record<PropertyKey, never>, TContext = Record<PropertyKey, never>, TArgs = Record<PropertyKey, never>> =
  | ((...args: any[]) => SubscriptionObject<TResult, TKey, TParent, TContext, TArgs>)
  | SubscriptionObject<TResult, TKey, TParent, TContext, TArgs>;

export type TypeResolveFn<TTypes, TParent = Record<PropertyKey, never>, TContext = Record<PropertyKey, never>> = (
  parent: TParent,
  context: TContext,
  info: GraphQLResolveInfo
) => Maybe<TTypes> | Promise<Maybe<TTypes>>;

export type IsTypeOfResolverFn<T = Record<PropertyKey, never>, TContext = Record<PropertyKey, never>> = (obj: T, context: TContext, info: GraphQLResolveInfo) => boolean | Promise<boolean>;

export type NextResolverFn<T> = () => Promise<T>;

export type DirectiveResolverFn<TResult = Record<PropertyKey, never>, TParent = Record<PropertyKey, never>, TContext = Record<PropertyKey, never>, TArgs = Record<PropertyKey, never>> = (
  next: NextResolverFn<TResult>,
  parent: TParent,
  args: TArgs,
  context: TContext,
  info: GraphQLResolveInfo
) => TResult | Promise<TResult>;




/** Mapping of interface types */
export type ResolversInterfaceTypes<_RefType extends Record<string, unknown>> = {
  Traceable: never;
};

/** Mapping between all available schema types and the resolvers types */
export type ResolversTypes = {
  AdminLevel: AdminLevel;
  BookGenre: BookGenre;
  Boolean: ResolverTypeWrapper<Scalars['Boolean']['output']>;
  ConflictType: ConflictType;
  CredibilityTier: CredibilityTier;
  DatePrecision: DatePrecision;
  DateTime: ResolverTypeWrapper<Scalars['DateTime']['output']>;
  EventType: EventType;
  HistoricalDate: ResolverTypeWrapper<HistoricalDate>;
  HypothesisRelationType: HypothesisRelationType;
  ID: ResolverTypeWrapper<Scalars['ID']['output']>;
  Int: ResolverTypeWrapper<Scalars['Int']['output']>;
  JSON: ResolverTypeWrapper<Scalars['JSON']['output']>;
  MultiLangText: ResolverTypeWrapper<MultiLangText>;
  NameType: NameType;
  PositiveInt: ResolverTypeWrapper<Scalars['PositiveInt']['output']>;
  ProvenanceTier: ProvenanceTier;
  Query: ResolverTypeWrapper<Record<PropertyKey, never>>;
  RealityStatus: RealityStatus;
  String: ResolverTypeWrapper<Scalars['String']['output']>;
  Traceable: ResolverTypeWrapper<ResolversInterfaceTypes<ResolversTypes>['Traceable']>;
  UUID: ResolverTypeWrapper<Scalars['UUID']['output']>;
};

/** Mapping between all available schema types and the resolvers parents */
export type ResolversParentTypes = {
  Boolean: Scalars['Boolean']['output'];
  DateTime: Scalars['DateTime']['output'];
  HistoricalDate: HistoricalDate;
  ID: Scalars['ID']['output'];
  Int: Scalars['Int']['output'];
  JSON: Scalars['JSON']['output'];
  MultiLangText: MultiLangText;
  PositiveInt: Scalars['PositiveInt']['output'];
  Query: Record<PropertyKey, never>;
  String: Scalars['String']['output'];
  Traceable: ResolversInterfaceTypes<ResolversParentTypes>['Traceable'];
  UUID: Scalars['UUID']['output'];
};

export interface DateTimeScalarConfig extends GraphQLScalarTypeConfig<ResolversTypes['DateTime'], any> {
  name: 'DateTime';
}

export type HistoricalDateResolvers<ContextType = unknown, ParentType extends ResolversParentTypes['HistoricalDate'] = ResolversParentTypes['HistoricalDate']> = {
  day?: Resolver<Maybe<ResolversTypes['Int']>, ParentType, ContextType>;
  lunarDay?: Resolver<Maybe<ResolversTypes['Int']>, ParentType, ContextType>;
  lunarMonth?: Resolver<Maybe<ResolversTypes['Int']>, ParentType, ContextType>;
  month?: Resolver<Maybe<ResolversTypes['Int']>, ParentType, ContextType>;
  originalText?: Resolver<Maybe<ResolversTypes['String']>, ParentType, ContextType>;
  polityId?: Resolver<Maybe<ResolversTypes['UUID']>, ParentType, ContextType>;
  precision?: Resolver<ResolversTypes['DatePrecision'], ParentType, ContextType>;
  reignEra?: Resolver<Maybe<ResolversTypes['String']>, ParentType, ContextType>;
  reignYear?: Resolver<Maybe<ResolversTypes['PositiveInt']>, ParentType, ContextType>;
  season?: Resolver<Maybe<ResolversTypes['String']>, ParentType, ContextType>;
  sexagenaryYear?: Resolver<Maybe<ResolversTypes['String']>, ParentType, ContextType>;
  yearMax?: Resolver<Maybe<ResolversTypes['Int']>, ParentType, ContextType>;
  yearMin?: Resolver<Maybe<ResolversTypes['Int']>, ParentType, ContextType>;
};

export interface JsonScalarConfig extends GraphQLScalarTypeConfig<ResolversTypes['JSON'], any> {
  name: 'JSON';
}

export type MultiLangTextResolvers<ContextType = unknown, ParentType extends ResolversParentTypes['MultiLangText'] = ResolversParentTypes['MultiLangText']> = {
  en?: Resolver<Maybe<ResolversTypes['String']>, ParentType, ContextType>;
  zhHans?: Resolver<ResolversTypes['String'], ParentType, ContextType>;
  zhHant?: Resolver<Maybe<ResolversTypes['String']>, ParentType, ContextType>;
};

export interface PositiveIntScalarConfig extends GraphQLScalarTypeConfig<ResolversTypes['PositiveInt'], any> {
  name: 'PositiveInt';
}

export type QueryResolvers<ContextType = unknown, ParentType extends ResolversParentTypes['Query'] = ResolversParentTypes['Query']> = {
  _schemaVersion?: Resolver<ResolversTypes['String'], ParentType, ContextType>;
};

export type TraceableResolvers<ContextType = unknown, ParentType extends ResolversParentTypes['Traceable'] = ResolversParentTypes['Traceable']> = {
  __resolveType: TypeResolveFn<null, ParentType, ContextType>;
};

export interface UuidScalarConfig extends GraphQLScalarTypeConfig<ResolversTypes['UUID'], any> {
  name: 'UUID';
}

export type Resolvers<ContextType = unknown> = {
  DateTime?: GraphQLScalarType;
  HistoricalDate?: HistoricalDateResolvers<ContextType>;
  JSON?: GraphQLScalarType;
  MultiLangText?: MultiLangTextResolvers<ContextType>;
  PositiveInt?: GraphQLScalarType;
  Query?: QueryResolvers<ContextType>;
  Traceable?: TraceableResolvers<ContextType>;
  UUID?: GraphQLScalarType;
};

