/**
 * graphql-codegen configuration for @huadian/api.
 *
 * Reads the merged SDL snapshot at src/schema/__snapshot__/schema.graphql
 * (produced by scripts/merge-schema.ts) and emits TypeScript types +
 * resolver signatures to src/__generated__/graphql.ts.
 *
 * Architect rulings:
 * - Q-6: graphql-codegen introduced in T-P0-003 (schema-first + codegen).
 * - R-2(a): SDL merged via @graphql-tools loadFilesSync + mergeTypeDefs
 *   before codegen runs (see scripts/merge-schema.ts).
 * - R-3: scalar whitelist enforced at SDL level; scalars map listed below
 *   must not grow without a new ADR.
 */
import type { CodegenConfig } from "@graphql-codegen/cli";

const config: CodegenConfig = {
  overwrite: true,
  // Snapshot is the single executable schema; CI step ① diffs this file.
  schema: "./src/schema/__snapshot__/schema.graphql",
  generates: {
    "./src/__generated__/graphql.ts": {
      plugins: [
        {
          add: {
            content:
              "// AUTO-GENERATED by graphql-codegen (T-P0-003). DO NOT EDIT.\n" +
              "// Regenerate via: pnpm --filter @huadian/api codegen",
          },
        },
        "typescript",
        "typescript-resolvers",
      ],
      config: {
        // R-3 scalar whitelist — mirrors services/api/src/schema/scalars.graphql
        scalars: {
          DateTime: "string",
          UUID: "string",
          JSON: "unknown",
          PositiveInt: "number",
        },
        useTypeImports: true,
        enumsAsTypes: false,
        avoidOptionals: {
          field: true,
          inputValue: false,
          object: true,
          defaultValue: true,
        },
        // Resolver context is wired in subtask 4 (src/context.ts).
        // Until then the resolver signatures carry an opaque context.
        contextType: "unknown",
      },
    },
  },
};

export default config;
