"""Core data types for the audit_triage framework.

These types are the contract between the framework and its consumers.
Keep them stable across v0.x releases; deprecate before changing.

Three families:

1. Decision verdicts and item kinds
   - ``TriageDecisionType`` — the three verdicts (approve / reject / defer)
   - ``ItemKind`` — opaque domain-friendly identifier for one kind of pending
     review item (e.g. ``"seed_mapping"`` / ``"guard_blocked_merge"``)

2. Domain row projections
   - ``PendingItem`` — one row in the pending review queue
   - ``DecisionRecord`` — one row in the audit trail (``triage_decisions``)
   - ``RecordDecisionInput`` — input payload to record a new decision
   - ``RecordDecisionResult`` — service-layer result (success row + next pending
     id, or structured error)

3. Plugin protocols (item kind registry — DB-table mapping & decision applier
   stub live here so callers don't have to import from 4 places)
   - ``ItemKindRegistry`` — bridges domain ``ItemKind`` to DB ``source_table``
   - ``DecisionApplier`` — V0.2 hook (post-decision data mutation); V0.1
     contract is **zero-downstream** (per ADR-027 §2.5 / §5 merge-iron-rule)

License: Apache 2.0
Source: extracted from services/api/src/services/triage.service.ts (TS prod)
        + services/pipeline/migrations/0014_add_triage_decisions.sql
        + ADR-027 (Pending Triage UI Workflow Protocol)
        + methodology/05-audit-trail-pattern.md
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Literal, Protocol, runtime_checkable

# ---------------------------------------------------------------------------
# Decision verdict + item kind
# ---------------------------------------------------------------------------

#: Decision verdict recorded against a pending triage item. Mirrors the
#: ``triage_decisions.decision`` CHECK constraint; lower-case in DB.
TriageDecisionType = Literal["approve", "reject", "defer"]

ALL_DECISION_TYPES: tuple[TriageDecisionType, ...] = ("approve", "reject", "defer")

#: Domain-friendly identifier for one kind of pending review item.
#: Opaque string; the case domain is responsible for choosing identifiers
#: and registering them via :class:`ItemKindRegistry`.
#:
#: HuaDian uses ``"seed_mapping"`` and ``"guard_blocked_merge"``; a legal
#: domain might use ``"contract_party_match"`` and ``"clause_revision"``.
ItemKind = str


# ---------------------------------------------------------------------------
# Domain row projections
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class PendingItem:
    """One row in the pending review queue.

    Conceptually the union of multiple source tables (e.g. ``seed_mappings``
    + ``pending_merge_reviews`` in HuaDian). The case-specific store
    implementation joins those tables under a common projection.

    Attributes:
        item_id:        composite ``"<kind>:<source_id>"`` identifier
                        suitable for opaque transport (REST/GraphQL ID).
        kind:           domain ItemKind ("seed_mapping" / etc).
        source_table:   physical DB table the source row lives in.
        source_id:      UUID of the source row (string for transport).
        surface:        the canonical "surface text" — usually a person /
                        entity name, used for cluster sort + hint banner.
        pending_since:  when the source row entered ``pending`` state.
        raw_payload:    case-specific fields needed by downstream rendering
                        (target_entity_id / dictionary_entry_id / etc).
                        Treated as opaque by the framework.
    """

    item_id: str
    kind: ItemKind
    source_table: str
    source_id: str
    surface: str
    pending_since: datetime
    raw_payload: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True, slots=True)
class DecisionRecord:
    """One row in the ``triage_decisions`` audit table.

    Multi-row audit per source_id allowed (defer → revisit → approve).
    Application layer queries "latest decision per source_id" via
    ``decided_at DESC`` to get the effective verdict.

    Attributes:
        id:                       UUID generated by the store on INSERT.
        source_table:             physical DB table the source row lives in.
        source_id:                logical FK to ``<source_table>.id``;
                                  not enforced via SQL FK due to backfill /
                                  cross-table complexity (ADR-027 §3).
        surface_snapshot:         surface text at decision time. **Required**
                                  because the source row's surface may
                                  mutate later (rename / soft-delete).
        decision:                 verdict (approve / reject / defer).
        reason_text:              free-form decision rationale (markdown).
        reason_source_type:       one of REASON_SOURCE_TYPES (or None).
        historian_id:             id of the decision-maker.
        historian_commit_ref:     optional git commit hash referencing the
                                  historian's external review notes.
        architect_ack_ref:        optional git commit hash for architect
                                  inline ACK scenarios.
        decided_at:               DB-side default ``now()``.
        downstream_applied:       V0.2 hook — set by :class:`DecisionApplier`
                                  after applying the decision to the source
                                  data layer. V0.1 always inserts as ``False``.
        downstream_applied_at:    when downstream apply ran.
        downstream_applied_by:    id of the V2 async job that applied.
        notes:                    free-form notes (e.g., diagnostics).
    """

    id: str
    source_table: str
    source_id: str
    surface_snapshot: str
    decision: TriageDecisionType
    historian_id: str
    decided_at: datetime
    reason_text: str | None = None
    reason_source_type: str | None = None
    historian_commit_ref: str | None = None
    architect_ack_ref: str | None = None
    downstream_applied: bool = False
    downstream_applied_at: datetime | None = None
    downstream_applied_by: str | None = None
    notes: str | None = None


@dataclass(frozen=True, slots=True)
class RecordDecisionInput:
    """Input payload for :func:`framework.audit_triage.service.record_decision`.

    ``item_id`` is the composite ``"<kind>:<source_id>"`` identifier —
    same shape as :attr:`PendingItem.item_id`.
    """

    item_id: str
    decision: TriageDecisionType
    historian_id: str
    reason_text: str | None = None
    reason_source_type: str | None = None
    historian_commit_ref: str | None = None
    architect_ack_ref: str | None = None
    notes: str | None = None


# ---------------------------------------------------------------------------
# Service-layer result
# ---------------------------------------------------------------------------

#: Structured error code returned by :func:`record_decision`. Stable across
#: v0.x; new codes may be added (always at the end of this list).
DecisionErrorCode = Literal[
    "UNAUTHORIZED",
    "INVALID_TRANSITION",
    "ITEM_NOT_FOUND",
    "INVALID_REASON_SOURCE_TYPE",
    "INVALID_DECISION_TYPE",
    "INVALID_ITEM_ID_FORMAT",
]


@dataclass(frozen=True, slots=True)
class DecisionError:
    """Structured error: when non-null, the decision did not persist.

    The application layer should display ``message`` and keep the form
    state so the historian can correct + resubmit.
    """

    code: DecisionErrorCode
    message: str


@dataclass(frozen=True, slots=True)
class RecordDecisionResult:
    """Service-layer result of :func:`record_decision`.

    On success: ``decision_record`` is set, ``error`` is None, and
    ``next_pending_item_id`` may be a string (next item in the inbox queue)
    or None (queue empty).

    On failure: ``decision_record`` is None, ``error`` is set, and
    ``next_pending_item_id`` is None.
    """

    decision_record: DecisionRecord | None
    next_pending_item_id: str | None
    error: DecisionError | None


# ---------------------------------------------------------------------------
# Plugin Protocols (small ones — store / authz / reasons live in their own
# modules; these two stay here so callers can import from one place)
# ---------------------------------------------------------------------------


@runtime_checkable
class ItemKindRegistry(Protocol):
    """Bridges domain :data:`ItemKind` to the physical DB ``source_table``.

    Why a Protocol instead of a hard-coded dict: the framework cannot
    know what kinds the case domain will use. A registry also lets the
    domain validate "is this an allowed kind?" centrally.

    Reference impl: see :class:`StaticItemKindRegistry` in
    ``examples/huadian_classics/``.
    """

    def kind_to_source_table(self, kind: ItemKind) -> str:
        """Return the physical DB table for ``kind``. Raise ``KeyError``
        when the kind is not registered."""
        ...

    def all_kinds(self) -> tuple[ItemKind, ...]:
        """Return the full tuple of registered kinds (used for filter
        validation and UI dropdowns)."""
        ...


@runtime_checkable
class DecisionApplier(Protocol):
    """**V0.2 hook** — post-decision data mutation.

    V0.1 contract is **zero-downstream** (per ADR-027 §2.5 + §5):
    decisions write to ``triage_decisions`` only; the source data layer
    (``persons`` / ``merge_log`` / etc) is NOT touched. V0.2 will add
    an async job that picks up rows where ``downstream_applied=false``
    and applies the verdict (e.g. an APPROVE on a merge candidate
    triggers the actual merge).

    This Protocol is included in v0.1 so consumers can plan their
    integration shape, but no framework-shipped implementation exists.
    Calling :func:`framework.audit_triage.service.apply_pending` (when
    that ships in v0.2) without an Applier will be a no-op.
    """

    async def apply(self, record: DecisionRecord) -> None:
        """Apply ``record``'s verdict to the source data layer.

        Implementations should be idempotent: the framework may retry
        on transient failures.
        """
        ...
