/**
 * Merge all SDL fragments under src/schema/**\/*.graphql into a single
 * canonical snapshot at src/schema/__snapshot__/schema.graphql.
 *
 * Architect ruling R-2(a): use @graphql-tools loadFilesSync + mergeTypeDefs.
 *
 * The snapshot is the source of truth for:
 *   - graphql-codegen (see codegen.ts)
 *   - graphql-inspector breaking diff in CI (R-2(b) step ②)
 *   - CI codegen:verify (R-2(b) step ①: git diff --exit-code on this file)
 *
 * Contract: this script MUST be deterministic. Any change in output that
 * is not caused by a SDL source change indicates a bug here.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { print } from "graphql";
import { loadFilesSync } from "@graphql-tools/load-files";
import { mergeTypeDefs } from "@graphql-tools/merge";

const __dirname = dirname(fileURLToPath(import.meta.url));
const API_ROOT = resolve(__dirname, "..");
const SCHEMA_DIR = join(API_ROOT, "src", "schema");
const SNAPSHOT_DIR = join(SCHEMA_DIR, "__snapshot__");
const SNAPSHOT_FILE = join(SNAPSHOT_DIR, "schema.graphql");

// Deliberately exclude the snapshot itself to avoid self-inclusion.
const SDL_GLOB = join(SCHEMA_DIR, "**/*.graphql");
const IGNORE = [join(SNAPSHOT_DIR, "**/*.graphql")];

function main(): void {
  const typesArray = loadFilesSync(SDL_GLOB, {
    ignoredExtensions: [],
    extensions: ["graphql"],
    recursive: true,
    globOptions: {
      ignore: IGNORE,
    },
  });

  if (typesArray.length === 0) {
    throw new Error(
      `No SDL files found under ${relative(API_ROOT, SCHEMA_DIR)}. ` +
        "Create at least one *.graphql file before running schema:merge.",
    );
  }

  const merged = mergeTypeDefs(typesArray, {
    // Keep field order; prevent accidental churn across merges.
    sort: true,
    throwOnConflict: true,
    useSchemaDefinition: true,
  });

  const header =
    "# AUTO-GENERATED by scripts/merge-schema.ts (T-P0-003). DO NOT EDIT.\n" +
    "# Source: services/api/src/schema/**/*.graphql\n" +
    "# Regenerate via: pnpm --filter @huadian/api schema:merge\n\n";

  const body = print(merged);
  const output = header + body + (body.endsWith("\n") ? "" : "\n");

  mkdirSync(SNAPSHOT_DIR, { recursive: true });
  writeFileSync(SNAPSHOT_FILE, output, "utf8");

  const rel = relative(API_ROOT, SNAPSHOT_FILE);
  console.info(
    `[schema:merge] merged ${String(typesArray.length)} SDL file(s) → ${rel}`,
  );
}

main();
